# Instalar pacotes básicos necessários

- name: Instalar dependências essenciais
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

# Adicionar a chave GPG oficial do Docker

- name: Adicionar chave GPG do Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# Adicionar o repositório do Docker para Ubuntu

- name: Adicionar repositório do Docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

# Instalar o Docker

- name: Instalar Docker Engine
  apt:
    name: docker-ce
    state: latest
    update_cache: yes

# Instalar Docker Compose manualmente
# O Docker Compose não é mais um pacote .deb e precisa ser instalado como binário

- name: Baixar Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

# Adicionar usuário ao grupo docker (para usar sem sudo)

- name: Adicionar usuário ao grupo docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

# Ativar e iniciar o serviço Docker
# Após a adição ao grupo, o usuário precisa relogar para aplicar
- name: Ativar e iniciar serviço Docker
  systemd:
    name: docker
    enabled: yes
    state: started

